// Target firms for the search, matched to a turnaround/restructuring and M&A
// background. Supplied as names and domains only — no ATS tokens — so the
// scraper discovers each firm's job board at runtime (see discoverAts in
// fetch-jobs.mjs) and caches what it finds.
//
// Many of these run Workday, iCIMS or proprietary portals with no public JSON
// API. Those will never resolve here and have to be applied to directly; the
// health report names them.

export const TARGETS = [
  { name: 'Alvarez & Marsal', domain: 'alvarezandmarsal.com', category: 'restructuring_advisory', whyFit: 'Largest pure play turnaround firm; direct match to your T&R background' },
  { name: 'AlixPartners', domain: 'alixpartners.com', category: 'restructuring_advisory', whyFit: 'Operational turnaround and performance improvement; hires ex Big Four T&R' },
  { name: 'FTI Consulting', domain: 'fticonsulting.com', category: 'restructuring_advisory', whyFit: 'Corporate finance and restructuring segment with a Dublin office' },
  { name: 'Kroll', domain: 'kroll.com', category: 'restructuring_advisory', whyFit: 'Restructuring, valuation and receivership work; strong Ireland presence' },
  { name: 'Teneo', domain: 'teneo.com', category: 'restructuring_advisory', whyFit: 'Absorbed the Deloitte UK restructuring practice; active Irish insolvency team' },
  { name: 'Interpath', domain: 'interpath.com', category: 'restructuring_advisory', whyFit: 'Spun out of KPMG UK restructuring; growing Dublin team' },
  { name: 'Ankura', domain: 'ankura.com', category: 'restructuring_advisory', whyFit: 'Turnaround and restructuring plus disputes' },
  { name: 'Berkeley Research Group', domain: 'thinkbrg.com', category: 'restructuring_advisory', whyFit: 'Corporate finance and restructuring practice' },
  { name: 'Riveron', domain: 'riveron.com', category: 'restructuring_advisory', whyFit: 'Absorbed Conway MacKenzie; middle market turnaround' },
  { name: 'Portage Point Partners', domain: 'pppllc.com', category: 'restructuring_advisory', whyFit: 'Fast growing US turnaround boutique, hires at analyst level' },
  { name: 'M3 Partners', domain: 'm3-partners.com', category: 'restructuring_advisory', whyFit: 'Debtor and creditor side restructuring advisory' },
  { name: 'Province', domain: 'provincefirm.com', category: 'restructuring_advisory', whyFit: 'Creditor committee advisory, heavy Chapter 11 flow' },
  { name: 'CR3 Partners', domain: 'cr3partners.com', category: 'restructuring_advisory', whyFit: 'Interim management and turnaround' },
  { name: 'Getzler Henrich', domain: 'getzlerhenrich.com', category: 'restructuring_advisory', whyFit: 'Hilco owned middle market turnaround firm' },
  { name: 'Hilco Global', domain: 'hilcoglobal.com', category: 'restructuring_advisory', whyFit: 'Asset valuation and disposal; matches your asset disposal experience' },
  { name: 'Gordon Brothers', domain: 'gordonbrothers.com', category: 'restructuring_advisory', whyFit: 'Asset disposition and liquidation, direct overlap with receivership work' },
  { name: 'B. Riley Financial', domain: 'brileyfin.com', category: 'restructuring_advisory', whyFit: 'Advisory plus liquidation and appraisal services' },
  { name: 'Accordion', domain: 'accordion.com', category: 'restructuring_advisory', whyFit: 'Private equity focused CFO and finance office consulting' },
  { name: 'SierraConstellation Partners', domain: 'sierraconstellation.com', category: 'restructuring_advisory', whyFit: 'Interim management and turnaround, West and East coast' },
  { name: 'Carl Marks Advisors', domain: 'carlmarks.com', category: 'restructuring_advisory', whyFit: 'Operational restructuring boutique' },
  { name: 'Quantuma', domain: 'quantuma.com', category: 'restructuring_advisory', whyFit: 'K3 owned insolvency and advisory practice' },
  { name: 'Azets', domain: 'azets.com', category: 'restructuring_advisory', whyFit: 'Advisory and restructuring across Ireland and the UK' },
  { name: 'Deloitte', domain: 'deloitte.com', category: 'big_four_advisory', whyFit: 'Turnaround and restructuring plus transaction services' },
  { name: 'PwC', domain: 'pwc.com', category: 'big_four_advisory', whyFit: 'Business restructuring services and insolvency appointments' },
  { name: 'KPMG', domain: 'kpmg.com', category: 'big_four_advisory', whyFit: 'Restructuring and deal advisory' },
  { name: 'EY', domain: 'ey.com', category: 'big_four_advisory', whyFit: 'Internal moves to the US or a step up in the Dublin T&R team' },
  { name: 'Grant Thornton', domain: 'grantthornton.ie', category: 'big_four_advisory', whyFit: 'Financial services advisory and restructuring, large Dublin practice' },
  { name: 'BDO', domain: 'bdo.ie', category: 'big_four_advisory', whyFit: 'Business restructuring and corporate finance' },
  { name: 'Forvis Mazars', domain: 'forvismazars.com', category: 'big_four_advisory', whyFit: 'Restructuring services and transaction advisory' },
  { name: 'RSM', domain: 'rsm.global', category: 'big_four_advisory', whyFit: 'Restructuring advisory in the middle market' },
  { name: 'PJT Partners', domain: 'pjtpartners.com', category: 'restructuring_bank', whyFit: 'Restructuring and Special Situations Group, the premier RX franchise' },
  { name: 'Houlihan Lokey', domain: 'hl.com', category: 'restructuring_bank', whyFit: 'Ranked number one in completed restructuring transactions' },
  { name: 'Lazard', domain: 'lazard.com', category: 'restructuring_bank', whyFit: 'Restructuring and liability management practice' },
  { name: 'Rothschild & Co', domain: 'rothschildandco.com', category: 'restructuring_bank', whyFit: 'Debt advisory and restructuring, strong European flow' },
  { name: 'Evercore', domain: 'evercore.com', category: 'restructuring_bank', whyFit: 'Debt advisory and restructuring group' },
  { name: 'Moelis & Company', domain: 'moelis.com', category: 'restructuring_bank', whyFit: 'Recapitalisation and restructuring group' },
  { name: 'Perella Weinberg Partners', domain: 'pwpartners.com', category: 'restructuring_bank', whyFit: 'Restructuring practice with heavy creditor side work' },
  { name: 'Centerview Partners', domain: 'centerviewpartners.com', category: 'restructuring_bank', whyFit: 'Debt advisory and restructuring' },
  { name: 'Guggenheim Securities', domain: 'guggenheimpartners.com', category: 'restructuring_bank', whyFit: 'Restructuring and special situations advisory' },
  { name: 'Jefferies', domain: 'jefferies.com', category: 'restructuring_bank', whyFit: 'Debt advisory and restructuring plus leveraged finance' },
  { name: 'Ducera Partners', domain: 'ducerapartners.com', category: 'restructuring_bank', whyFit: 'Restructuring specialist boutique' },
  { name: 'Solomon Partners', domain: 'solomonpartners.com', category: 'restructuring_bank', whyFit: 'Restructuring and capital advisory' },
  { name: 'Stifel', domain: 'stifel.com', category: 'restructuring_bank', whyFit: 'Owns Miller Buckfire, the restructuring arm' },
  { name: 'Piper Sandler', domain: 'pipersandler.com', category: 'restructuring_bank', whyFit: 'Restructuring and special situations coverage' },
  { name: 'Cantor Fitzgerald', domain: 'cantor.com', category: 'restructuring_bank', whyFit: 'Investment banking in New York and a large Dublin operation' },
  { name: 'JPMorganChase', domain: 'jpmorganchase.com', category: 'bank', whyFit: 'Restructuring, leveraged finance and Dublin operations' },
  { name: 'Goldman Sachs', domain: 'goldmansachs.com', category: 'bank', whyFit: 'Special situations group and financing' },
  { name: 'Morgan Stanley', domain: 'morganstanley.com', category: 'bank', whyFit: 'Restructuring within global capital markets' },
  { name: 'Bank of America', domain: 'bankofamerica.com', category: 'bank', whyFit: 'Leveraged finance and restructuring coverage' },
  { name: 'Citi', domain: 'citigroup.com', category: 'bank', whyFit: 'Restructuring team and large Dublin footprint' },
  { name: 'Barclays', domain: 'barclays.com', category: 'bank', whyFit: 'Capital solutions and restructuring, Dublin entity' },
  { name: 'Deutsche Bank', domain: 'db.com', category: 'bank', whyFit: 'Debt advisory and workout, Dublin office' },
  { name: 'UBS', domain: 'ubs.com', category: 'bank', whyFit: 'Liability management and financing solutions' },
  { name: 'HSBC', domain: 'hsbc.com', category: 'bank', whyFit: 'Loan workout and restructuring unit' },
  { name: 'BNP Paribas', domain: 'bnpparibas.com', category: 'bank', whyFit: 'Debt restructuring and Dublin operations' },
  { name: 'Wells Fargo', domain: 'wellsfargo.com', category: 'bank', whyFit: 'Large Dublin office plus US restructuring coverage' },
  { name: 'RBC Capital Markets', domain: 'rbc.com', category: 'bank', whyFit: 'Restructuring advisory and a growing Dublin base' },
  { name: 'Nomura', domain: 'nomura.com', category: 'bank', whyFit: 'Credit and special situations' },
  { name: 'Macquarie', domain: 'macquarie.com', category: 'bank', whyFit: 'Principal finance and special situations, Dublin presence' },
  { name: 'Oaktree Capital Management', domain: 'oaktreecapital.com', category: 'credit_fund', whyFit: 'The benchmark distressed debt manager, Dublin entity' },
  { name: 'Apollo Global Management', domain: 'apollo.com', category: 'credit_fund', whyFit: 'Credit and hybrid value, large Irish presence' },
  { name: 'Ares Management', domain: 'aresmgmt.com', category: 'credit_fund', whyFit: 'Private credit and special opportunities, Dublin office' },
  { name: 'Cerberus Capital Management', domain: 'cerberus.com', category: 'credit_fund', whyFit: 'Distressed and operational turnaround; bought Irish loan books' },
  { name: 'Fortress Investment Group', domain: 'fortress.com', category: 'credit_fund', whyFit: 'Credit and real assets, active in Irish distressed loans' },
  { name: 'Centerbridge Partners', domain: 'centerbridge.com', category: 'credit_fund', whyFit: 'Distressed for control and credit' },
  { name: 'Silver Point Capital', domain: 'silverpointcapital.com', category: 'credit_fund', whyFit: 'Distressed credit specialist' },
  { name: 'Anchorage Capital Group', domain: 'anchoragecapital.com', category: 'credit_fund', whyFit: 'Illiquid credit and distressed' },
  { name: 'Knighthead Capital', domain: 'knightheadcapital.com', category: 'credit_fund', whyFit: 'Distressed and event driven credit' },
  { name: 'Monarch Alternative Capital', domain: 'monarchlp.com', category: 'credit_fund', whyFit: 'Distressed debt across US and Europe' },
  { name: 'King Street Capital Management', domain: 'kingstreet.com', category: 'credit_fund', whyFit: 'Distressed and event driven' },
  { name: 'Marathon Asset Management', domain: 'marathonfund.com', category: 'credit_fund', whyFit: 'Global credit and special situations' },
  { name: 'GoldenTree Asset Management', domain: 'goldentree.com', category: 'credit_fund', whyFit: 'Credit manager with a Dublin office' },
  { name: 'Bain Capital Credit', domain: 'baincapitalcredit.com', category: 'credit_fund', whyFit: 'Distressed and special situations, Dublin office' },
  { name: 'Blackstone', domain: 'blackstone.com', category: 'credit_fund', whyFit: 'Credit and insurance arm, Dublin office' },
  { name: 'KKR', domain: 'kkr.com', category: 'credit_fund', whyFit: 'Credit and special situations, Dublin entity' },
  { name: 'Carlyle', domain: 'carlyle.com', category: 'credit_fund', whyFit: 'Global credit and opportunistic strategies' },
  { name: 'Sixth Street', domain: 'sixthstreet.com', category: 'credit_fund', whyFit: 'Opportunistic credit, Dublin office' },
  { name: 'HPS Investment Partners', domain: 'hpspartners.com', category: 'credit_fund', whyFit: 'Private credit and special situations' },
  { name: 'Davidson Kempner', domain: 'dkp.com', category: 'credit_fund', whyFit: 'Distressed and event driven, Dublin office' },
  { name: 'Attestor Capital', domain: 'attestorcapital.com', category: 'credit_fund', whyFit: 'Distressed and special situations with Irish exposure' },
  { name: 'TPG Angelo Gordon', domain: 'angelogordon.com', category: 'credit_fund', whyFit: 'Distressed and corporate credit' },
  { name: 'Diameter Capital Partners', domain: 'diametercap.com', category: 'credit_fund', whyFit: 'Credit and special situations' },
  { name: 'Beach Point Capital', domain: 'beachpointcapital.com', category: 'credit_fund', whyFit: 'Credit manager with a Dublin office' },
  { name: 'Lone Star Funds', domain: 'lonestarfunds.com', category: 'credit_fund', whyFit: 'Distressed asset buyer, Hudson Advisors services Irish loans' },
  { name: 'H.I.G. Capital', domain: 'higcapital.com', category: 'credit_fund', whyFit: 'Bayside distressed arm plus a Dublin office' },
  { name: 'Platinum Equity', domain: 'platinumequity.com', category: 'private_equity', whyFit: 'Buys underperforming carve outs, operational focus' },
  { name: 'Sun Capital Partners', domain: 'suncappart.com', category: 'private_equity', whyFit: 'Turnaround focused buyout firm' },
  { name: 'Atlas Holdings', domain: 'atlasholdingsllc.com', category: 'private_equity', whyFit: 'Industrial turnarounds and distressed acquisitions' },
  { name: 'AIB', domain: 'aib.ie', category: 'ireland_financial', whyFit: 'Workout, recoveries and corporate finance teams' },
  { name: 'Bank of Ireland', domain: 'bankofireland.com', category: 'ireland_financial', whyFit: 'Business restructuring and corporate banking' },
  { name: 'Pepper Advantage', domain: 'pepperadvantage.com', category: 'ireland_financial', whyFit: 'Credit servicing and loan workout' },
  { name: 'Davy', domain: 'davy.ie', category: 'ireland_financial', whyFit: 'Corporate finance and capital markets' },
  { name: 'Goodbody', domain: 'goodbody.ie', category: 'ireland_financial', whyFit: 'Corporate finance, debt advisory and research' },
  { name: 'Investec', domain: 'investec.com', category: 'ireland_financial', whyFit: 'Corporate finance and specialist lending in Dublin' },
  { name: 'EssilorLuxottica', domain: 'essilorluxottica.com', category: 'corporate_development', whyFit: 'Former employer; corporate development and finance roles' },
  { name: 'Flutter Entertainment', domain: 'flutter.com', category: 'corporate_development', whyFit: 'Dual listed, active corporate development team' },
  { name: 'CRH', domain: 'crh.com', category: 'corporate_development', whyFit: 'Serial acquirer with a New York listing and Dublin roots' },
  { name: 'Smurfit Westrock', domain: 'smurfitwestrock.com', category: 'corporate_development', whyFit: 'Post merger integration and corporate finance roles' },
  { name: 'Kerry Group', domain: 'kerry.com', category: 'corporate_development', whyFit: 'Corporate development and portfolio reshaping' },
  { name: 'Ryanair', domain: 'ryanair.com', category: 'corporate_development', whyFit: 'Treasury, financial planning and analysis roles in Dublin' },
];
